# Generated by Django 3.0.2 on 2020-03-01 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Organization', verbose_name='上级组织')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=10, unique=True, verbose_name='工作证号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('category', models.CharField(blank=True, max_length=10, verbose_name='类别')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='手机')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='返京日期或计划返京日期')),
                ('remark', models.TextField(blank=True, verbose_name='问题与意见')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Organization', verbose_name='单位')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='体温')),
                ('has_fever', models.NullBooleanField(verbose_name='发烧')),
                ('has_cough', models.NullBooleanField(verbose_name='咳嗽')),
                ('has_wornout', models.NullBooleanField(verbose_name='乏力')),
                ('remark', models.TextField(blank=True, verbose_name='其他状况说明')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Person', verbose_name='人员')),
            ],
            options={
                'verbose_name': '健康打卡',
                'verbose_name_plural': '健康打卡',
            },
        ),
    ]
