# Generated by Django 3.0.3 on 2020-03-02 03:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='紧急联系人的电话，格式同上。', max_length=128, region=None, verbose_name='备用电话'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='最好填写手机号，如果是座机请加区号，如果是境外电话请加国际电话区号。', max_length=128, region=None, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='person',
            name='remark',
            field=models.TextField(blank=True, help_text='需要向学校反映的问题与意见', verbose_name='问题与意见'),
        ),
        migrations.AlterField(
            model_name='person',
            name='return_date',
            field=models.DateField(blank=True, help_text='若暂无返京计划，可留空。', null=True, verbose_name='返京日期或计划返京日期'),
        ),
        migrations.AlterField(
            model_name='person',
            name='remark',
            field=models.TextField(blank=True, verbose_name='问题与意见'),
        ),
    ]
