# Generated by Django 3.0.3 on 2020-03-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_more_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='has_cough',
            field=models.BooleanField(default=False, verbose_name='咳嗽'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='has_fever',
            field=models.BooleanField(default=False, verbose_name='发烧'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='has_wornout',
            field=models.BooleanField(default=False, verbose_name='乏力'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='has_cough',
            field=models.BooleanField(blank=True, null=True, verbose_name='咳嗽'),
        ),
        migrations.AlterField(
            model_name='record',
            name='has_fever',
            field=models.BooleanField(blank=True, null=True, verbose_name='发烧'),
        ),
        migrations.AlterField(
            model_name='record',
            name='has_wornout',
            field=models.BooleanField(blank=True, null=True, verbose_name='乏力'),
        ),
    ]
