# Generated by Django 3.0.3 on 2020-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contacting_organizations',
            field=models.ManyToManyField(related_name='contactors', to='report.Organization', verbose_name='联系组织'),
        ),
    ]
