# Generated by Django 3.0.3 on 2020-03-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_person_contacting_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='contacting_organizations',
            new_name='can_contact',
        ),
    ]
