# Generated by Django 3.0.3 on 2020-03-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_to_can_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '楼宇',
                'verbose_name_plural': '楼宇',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='can_approve1',
            field=models.ManyToManyField(blank=True, related_name='approvers1', to='report.Organization', verbose_name='部门审核'),
        ),
        migrations.AddField(
            model_name='person',
            name='can_approve2',
            field=models.ManyToManyField(blank=True, related_name='approvers2', to='report.Organization', verbose_name='干事审核'),
        ),
        migrations.AddField(
            model_name='person',
            name='can_approve3',
            field=models.ManyToManyField(blank=True, related_name='approvers3', to='report.Organization', verbose_name='主管审核'),
        ),
        migrations.AlterField(
            model_name='person',
            name='can_contact',
            field=models.ManyToManyField(related_name='contactors', to='report.Organization', verbose_name='联系'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('room', models.CharField(max_length=100, verbose_name='房间号')),
                ('purpose', models.CharField(max_length=100, verbose_name='事由')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('approve1_time', models.DateTimeField(blank=True, null=True, verbose_name='部门审核时间')),
                ('approve2_time', models.DateTimeField(blank=True, null=True, verbose_name='干事审核时间')),
                ('approve3_time', models.DateTimeField(blank=True, null=True, verbose_name='主管审核时间')),
                ('approve1_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries1', to='report.Person', verbose_name='部门审核人')),
                ('approve2_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries2', to='report.Person', verbose_name='干事审核人')),
                ('approve3_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries3', to='report.Person', verbose_name='主管审核人')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Building', verbose_name='楼宇')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Person', verbose_name='人员')),
                ('approve1_decision', models.NullBooleanField(verbose_name='部门审核意见')),
                ('approve2_decision', models.NullBooleanField(verbose_name='干事审核意见')),
                ('approve3_decision', models.NullBooleanField(verbose_name='主管审核意见')),
            ],
            options={
                'verbose_name': '进楼申请',
                'verbose_name_plural': '进楼申请',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='can_contact',
            field=models.ManyToManyField(blank=True, related_name='contactors', to='report.Organization', verbose_name='联系'),
        ),
    ]
