# Generated by Django 3.0.3 on 2020-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_no_null_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='has_cough',
            field=models.BooleanField(default=False, verbose_name='咳嗽'),
        ),
        migrations.AlterField(
            model_name='record',
            name='has_fever',
            field=models.BooleanField(default=False, verbose_name='发烧'),
        ),
        migrations.AlterField(
            model_name='record',
            name='has_wornout',
            field=models.BooleanField(default=False, verbose_name='乏力'),
        ),
    ]
