# Generated by Django 3.0.3 on 2020-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_person_is_welcomed'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='已提交'),
        ),
    ]
