# Generated by Django 3.0.2 on 2020-02-25 04:15

from django.db import migrations, models
import django.db.models.deletion
import uawg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0007_change_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='代码')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('members', models.ManyToManyField(to='report.Person', verbose_name='成员')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uawg.Post', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='代码')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('begin_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('deadline', models.DateTimeField(verbose_name='提交截止时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uawg.models.report_attachment_path, verbose_name='文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uawg.Report', verbose_name='报告')),
            ],
            options={
                'verbose_name': '报告附件',
                'verbose_name_plural': '报告附件',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uawg.Task', verbose_name='任务'),
        ),
    ]
