# Generated by Django 3.0.2 on 2020-02-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_change_help_text'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-post_time',), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AddField(
            model_name='notice',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
        migrations.AddField(
            model_name='notice',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='原始链接'),
        ),
        migrations.CreateModel(
            name='Ack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Notice', verbose_name='通知')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Person', verbose_name='人员')),
            ],
            options={
                'verbose_name': '确认',
                'verbose_name_plural': '确认',
            },
        ),
    ]
