# Generated by Django 3.0.2 on 2020-02-10 07:58

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_and_add_ack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=notice.models.notice_attachment_path, verbose_name='文件')),
                ('weight', models.IntegerField(default=0, help_text='决定附件排序，越大越靠前。', verbose_name='权重')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.Notice', verbose_name='通知')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ('-weight', 'file'),
            },
        ),
    ]
