# Generated by Django 3.0.2 on 2020-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_add_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='to_ack',
            field=models.BooleanField(default=False, verbose_name='是否需要确认'),
        ),
    ]
