# Generated by Django 3.0.2 on 2020-02-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_change_help_text'),
        ('notice', '0004_notice_to_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='acked_persons',
            field=models.ManyToManyField(related_name='acked_notices', through='notice.Ack', to='report.Person', verbose_name='已确认人员'),
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
    ]
