# Generated by Django 3.0.2 on 2020-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_notice_acked_persons_and_remove_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='重要标记'),
        ),
    ]
